### PR TITLE
spruce up ui, minor formatting

### PR DESCRIPTION
**Pull request by KTibow**
see latest comments for what this looks like.

### CODE REVIEW

**Comment by matthiasdebaat** [comment]
Thanks for cleaning up this page!

By removing the app and play store badges it also removes attention to the most prominent action (I think) we want to show. It would be better to upgrade them with the newer ones. Can we check if a user is viewing this page via our app? In that case we can drop these badges.

You have to click the icon button to open the link? Some of the icons need a label for users to understand what it mean, for example discord. Maybe is a [`list`](https://m3.material.io/components/lists/guidelines) a better option. In the current design and on our settings tip we also call it chat, instead of Discord.
CleanShot 2023-05-15 at 11 07 36@2x

**Comment by KTibow** [comment]
by list, do you mean i should make it so each link is on its own row?

**Comment by KTibow** [comment]
> the authentication page is shown because the authentication page is not ready yet.

did you mean to say "the onboarding page is shown"?

**Comment by matthiasdebaat** [comment]
> > the authentication page is shown because the authentication page is not ready yet.
> 
> did you mean to say "the onboarding page is shown"?

Whoops, yes. Had a chat and looks like it's difficult to know if a user is viewing this page via our app? So skip this for now.

**Comment by KTibow** [comment]
@matthiasdebaat i went ahead and updated it to use the list style. i also changed the style a bit and removed some unused css while i was at it. it looks like this now:
image

**Comment by matthiasdebaat** [comment]
Nice! 

In English the title fits perfectly, what does it look like for other languages with more characters? Can you add chevrons to the list items?

**Comment by KTibow** [comment]
chevrons added :+1:
image

**Review by balloob — APPROVED** [review]

**Pull request merged**
